const TEXT_UI_EN = {
    HEADER: {
        MISSION_LABEL: "Mission",
    },
    SIDEBAR: {
        PROFILE_NAME: "Operative 7",
        STATUS_ONLINE: "Online",
        SECTION_STATUS: "Status",
        SECTION_INVENTORY: "Inventory",
    },
    MENU: {
        SAVE_GAME: "Save Game",
        LOAD_GAME: "Load Game",
        RESTART_MISSION: "Restart Mission",
        EXIT_SIMULATION: "Exit Simulation",
        CONFIRM_RESTART_TITLE: "RESTART MISSION?",
        CONFIRM_RESTART_MSG: "Current progress will be lost. Are you sure you want to abort this timeline?",
        CONFIRM_EXIT_TITLE: "TERMINATE SIMULATION?",
        CONFIRM_EXIT_MSG: "Any unsaved progress will be lost. Confirm disconnection?",
        CONFIRM_LOAD_TITLE: "OVERWRITE TIMELINE?",
        CONFIRM_LOAD_MSG: "Loading a new save will erase current progress. Proceed?",
        BTN_CONFIRM: "Confirm",
        BTN_CANCEL: "Cancel",
    },
    GAME_OVER: {
        TITLE: "Signal Lost",
        MESSAGE: "Vital signs critical. Connection terminated.",
        BUTTON_REBOOT: "Reboot System",
    },
    ERRORS: {
        SAVE_FAILED: "Failed to save game. See console for details.",
        LOAD_INVALID: "Failed to load save file: Invalid format.",
        LOAD_ERROR: "Error reading save file.",
        IMPORT_INVALID: "Invalid save file format",
        IMPORT_ERROR: "Error importing save:",
        UNKNOWN_MISSION: "Unknown Mission",
    },
    BUTTON_SUMMARY: "View Mission Progress",
    INPUT_PLACEHOLDER: "What is your next move?",
    INPUT_FOOTER: "Press Enter to send",
    TEMPLATES: {
        ACTION_INSPECT: "Inspecting {0}...",
    },
    API_MODAL: {
        TITLE: "API Configuration",
        SUBTITLE: "Enter your Google Gemini API Key",
        PLACEHOLDER: "AIzaSy...",
        PRIVACY_NOTE: "Your key is stored locally in your browser. It is never sent to any server other than Google's API.",
        BTN_TEST: "Test Key",
        BTN_SAVE: "Save",
        BTN_SAVE_CONFIG: "Save Configuration",
        STATUS_TESTING: "Verifying key with Google...",
        STATUS_SUCCESS: "Connection Successful! Key is valid.",
        ERR_EMPTY: "Please enter an API Key first.",
        LANGUAGE_LABEL: "Language (Optional)",
        LANGUAGE_PLACEHOLDER: "e.g. Indonesian, English, Japanese...",
    },
    API_ERRORS: {
        MISSING_KEY: "API Key is missing",
        EMPTY_KEY: "API Key is empty",
        INVALID_KEY: "Invalid API Key. Please check your key.",
        ACCESS_DENIED: "Access Denied. API Key may be invalid or restricted.",
        QUOTA_EXCEEDED: "Quota Exceeded. You have hit the rate limit.",
        SERVER_ERROR: "Google Server Error. Please try again later.",
        SERVICE_UNAVAILABLE: "Service Unavailable. Google servers are overloaded.",
        NETWORK_ERROR: "Network Error. Check your internet connection.",
        UNKNOWN_ERROR: "Unknown API Error",
        DEFAULT_FAIL: "Failed to connect to Gemini API.",
        JSON_PARSE: "The system glitched. Data corruption detected. (JSON Parse Error)",
    },
    CHARACTER_CREATION: {
        LOADING_TITLE: "INITIALIZING SUBJECT...",
        LOADING_SUBTITLE: "Generating neural patterns",
        ERROR_TITLE: "INITIALIZATION FAILURE",
        ERROR_DEFAULT: "Failed to initialize simulation parameters.",
        BTN_ABORT: "ABORT",
        BTN_RETRY: "RETRY SEQUENCE",
        BTN_ABORT_FULL: "ABORT SEQUENCE",
        TITLE: "IDENTITY CONSTRUCT",
        LABEL_NAME: "Subject Name",
        PLACEHOLDER_NAME: "Enter Name...",
        TITLE_RANDOMIZE: "Randomize Name",
        LABEL_ROLE: "Select Specialization",
        LOADOUT_TITLE: "Standard Issue Loadout",
        LOADOUT_DESC: "Start with role-specific equipment",
        STATS_TITLE: "Vital Statistics",
        EQUIPMENT_TITLE: "Equipment Manifest",
        BTN_INITIATE: "INITIATE SIMULATION",
    },
    GENRE_SELECTION: {
        TITLE: "NEXUS RPG",
        SUBTITLE: "Initialize your neural link. Select a simulation parameter.",
        BTN_SETTINGS: "Settings",
        BTN_RESUME: "RESUME MISSION",
        LABEL_ACTIVE: "SESSION ACTIVE",
        WARNING_TITLE: "Overwrite Session?",
        WARNING_MSG: "Starting a new simulation will erase your current progress. Are you sure?",
        BTN_CONFIRM: "Overwrite & Start",
        BTN_CANCEL: "Cancel",
        STATUS_GAME_OVER: "Previous Run Ended (Game Over)",
    },
    STATS: {
        HEALTH: "Health",
        ENERGY: "Energy",
        SHIELD: "Shield",
        SANITY: "Sanity",
        STAMINA: "Stamina",
        MOOD: "Mood",
        CHARM: "Charm",
    },
    GENRES: {
        SCIFI: {
            DESC: "High-tech, low-life. Neon lights and chrome.",
        },
        HORROR: {
            DESC: "Ancient madness in a derelict station.",
        },
        ROMANCE: {
            DESC: "Love and heartbreak in a digital age.",
        },
    },
    NARRATIVE: {
        PROCESSING: "Nexus processing...",
    }
};

const TEXT_UI_ID = {
    HEADER: {
        MISSION_LABEL: "Misi",
    },
    SIDEBAR: {
        PROFILE_NAME: "Operatif 7",
        STATUS_ONLINE: "Online",
        SECTION_STATUS: "Status",
        SECTION_INVENTORY: "Inventaris",
    },
    MENU: {
        SAVE_GAME: "Simpan Game",
        LOAD_GAME: "Muat Game",
        RESTART_MISSION: "Ulangi Misi",
        EXIT_SIMULATION: "Keluar Simulasi",
        CONFIRM_RESTART_TITLE: "ULANGI MISI?",
        CONFIRM_RESTART_MSG: "Progres saat ini akan hilang. Yakin ingin membatalkan timeline ini?",
        CONFIRM_EXIT_TITLE: "AKHIRI SIMULASI?",
        CONFIRM_EXIT_MSG: "Progres yang belum disimpan akan hilang. Konfirmasi pemutusan?",
        CONFIRM_LOAD_TITLE: "TIMPA TIMELINE?",
        CONFIRM_LOAD_MSG: "Memuat save baru akan menghapus progres saat ini. Lanjutkan?",
        BTN_CONFIRM: "Konfirmasi",
        BTN_CANCEL: "Batal",
    },
    GAME_OVER: {
        TITLE: "Sinyal Hilang",
        MESSAGE: "Tanda vital kritis. Koneksi terputus.",
        BUTTON_REBOOT: "Reboot Sistem",
    },
    ERRORS: {
        SAVE_FAILED: "Gagal menyimpan game. Cek konsol untuk detail.",
        LOAD_INVALID: "Gagal memuat file: Format tidak valid.",
        LOAD_ERROR: "Error membaca file simpanan.",
        IMPORT_INVALID: "Format file tidak valid",
        IMPORT_ERROR: "Error mengimpor:",
        UNKNOWN_MISSION: "Misi Tidak Diketahui",
    },
    BUTTON_SUMMARY: "Lihat Progres Misi",
    INPUT_PLACEHOLDER: "Apa langkah selanjutnya?",
    INPUT_FOOTER: "Tekan Enter untuk kirim",
    TEMPLATES: {
        ACTION_INSPECT: "Memeriksa {0}...",
    },
    API_MODAL: {
        TITLE: "Konfigurasi API",
        SUBTITLE: "Masukkan Google Gemini API Key Anda",
        PLACEHOLDER: "AIzaSy...",
        PRIVACY_NOTE: "Key Anda disimpan secara lokal di browser. Tidak pernah dikirim ke server selain Google API.",
        BTN_TEST: "Tes Key",
        BTN_SAVE: "Simpan",
        BTN_SAVE_CONFIG: "Simpan Konfigurasi",
        STATUS_TESTING: "Memverifikasi key dengan Google...",
        STATUS_SUCCESS: "Koneksi Berhasil! Key valid.",
        ERR_EMPTY: "Mohon masukkan API Key terlebih dahulu.",
        LANGUAGE_LABEL: "Bahasa (Opsional)",
        LANGUAGE_PLACEHOLDER: "cth. Indonesian, English, Japanese...",
    },
    API_ERRORS: {
        MISSING_KEY: "API Key hilang",
        EMPTY_KEY: "API Key kosong",
        INVALID_KEY: "API Key tidak valid. Cek key Anda.",
        ACCESS_DENIED: "Akses Ditolak. API Key mungkin salah atau dibatasi.",
        QUOTA_EXCEEDED: "Kuota Terlampaui. Anda mencapai batas rate limit.",
        SERVER_ERROR: "Google Server Error. Coba lagi nanti.",
        SERVICE_UNAVAILABLE: "Layanan Tidak Tersedia. Server Google sibuk.",
        NETWORK_ERROR: "Error Jaringan. Cek koneksi internet Anda.",
        UNKNOWN_ERROR: "Error API Tidak Diketahui",
        DEFAULT_FAIL: "Gagal terhubung ke Gemini API.",
        JSON_PARSE: "Sistem glitch. Korupsi data terdeteksi. (JSON Parse Error)",
    },
    CHARACTER_CREATION: {
        LOADING_TITLE: "MENGINISIALISASI SUBJEK...",
        LOADING_SUBTITLE: "Membuat pola saraf",
        ERROR_TITLE: "KEGAGALAN INISIALISASI",
        ERROR_DEFAULT: "Gagal menginisialisasi parameter simulasi.",
        BTN_ABORT: "BATALKAN",
        BTN_RETRY: "ULANGI SEKUENS",
        BTN_ABORT_FULL: "BATALKAN SEKUENS",
        TITLE: "KONSTRUKSI IDENTITAS",
        LABEL_NAME: "Nama Subjek",
        PLACEHOLDER_NAME: "Masukkan Nama...",
        TITLE_RANDOMIZE: "Acak Nama",
        LABEL_ROLE: "Pilih Spesialisasi",
        LOADOUT_TITLE: "Perlengkapan Standar",
        LOADOUT_DESC: "Mulai dengan peralatan khusus peran",
        STATS_TITLE: "Statistik Vital",
        EQUIPMENT_TITLE: "Manifes Peralatan",
        BTN_INITIATE: "MULAI SIMULASI",
    },
    GENRE_SELECTION: {
        TITLE: "NEXUS RPG",
        SUBTITLE: "Inisialisasi neural link. Pilih parameter simulasi.",
        BTN_SETTINGS: "Pengaturan",
        BTN_RESUME: "LANJUTKAN MISI",
        LABEL_ACTIVE: "SESI AKTIF",
        WARNING_TITLE: "Timpa Sesi?",
        WARNING_MSG: "Memulai simulasi baru akan menghapus progres saat ini. Anda yakin?",
        BTN_CONFIRM: "Timpa & Mulai",
        BTN_CANCEL: "Batal",
        STATUS_GAME_OVER: "Run Sebelumnya Berakhir (Game Over)",
    },
    STATS: {
        HEALTH: "Kesehatan",
        ENERGY: "Energi",
        SHIELD: "Perisai",
        SANITY: "Kewarasan",
        STAMINA: "Stamina",
        MOOD: "Mood",
        CHARM: "Pesona",
    },
    GENRES: {
        SCIFI: {
            DESC: "Teknologi tinggi, hidup rendah. Lampu neon dan krom.",
        },
        HORROR: {
            DESC: "Kegilaan kuno di stasiun terlantar.",
        },
        ROMANCE: {
            DESC: "Cinta dan patah hati di era digital.",
        },
    },
    NARRATIVE: {
        PROCESSING: "Nexus memproses...",
    }
};

export const TEXT_UI = TEXT_UI_EN; // Default export for backward compatibility

export const TRANSLATIONS = {
    'English': TEXT_UI_EN,
    'Indonesian': TEXT_UI_ID,
    'Bahasa Indonesia': TEXT_UI_ID, // Alias
    'ID': TEXT_UI_ID // Alias
};
